# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            whyn4
tagline:          'Quynh Nguyen'
description:      'A Vietnamese Software Engineer who is really passionate and work in the Singapore, Japan is my wishes.'
url:              http://quynh-nguyen.github.io
baseurl:          /

author:
  name:           'Quynh Nguyen'
  url:            https://github.com/Quynh-Nguyen

paginate:         5
paginate_path:    "/page/:num"

# Custom vars
version:          1.1.0
plugins:
   - jekyll-paginate

github:
  repo:           https://github.com/Quynh-Nguyen/quynh-nguyen.github.io

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      comments: true
